### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by allentown521** [AviranAbady/CookieBar2#28]
**version 1.1.4**
Fatal Exception: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
       at android.view.ViewGroup.addViewInner(ViewGroup.java:5235)
       at android.view.ViewGroup.addView(ViewGroup.java:5064)
       at android.view.ViewGroup.addView(ViewGroup.java:5004)
       at android.view.ViewGroup.addView(ViewGroup.java:4976)
       at org.aviran.cookiebar2.CookieBar$1.onDismiss(SourceFile:3)
       at org.aviran.cookiebar2.Cookie.cookieListenerDismiss(SourceFile:87)
       at org.aviran.cookiebar2.Cookie.access$400(SourceFile:3)
       at org.aviran.cookiebar2.Cookie$3.onAnimationEnd(SourceFile:3)
       at android.view.animation.Animation.dispatchAnimationEnd(Animation.java:1019)
       at android.view.animation.AnimationSet.getTransformation(AnimationSet.java:397)
       at android.view.animation.Animation.getTransformation(Animation.java:1038)
       at android.view.View.applyLegacyAnimation(View.java:21903)
       at android.view.View.draw(View.java:22019)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
       at android.view.View.draw(View.java:22353)
       at com.android.internal.policy.DecorView.draw(DecorView.java:806)
       at android.view.View.updateDisplayListIfDirty(View.java:21226)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:4106)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3833)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3104)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
       at android.view.Choreographer.doCallbacks(Choreographer.java:796)
       at android.view.Choreographer.doFrame(Choreographer.java:731)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)

**Comment by allentown521** [comment]
https://github.com/AviranAbady/CookieBar2/issues/20
It looks the same as this problem. I used the latest version 1.1.4 at the beginning, and it has appeared several times.

**Comment by AviranAbady** [comment]
Hey @allentown521 
Please provide steps to reproduce the crash

**Comment by allentown521** [comment]
Sorry for not being able to provide, it is the log reported by the user

Aviran Abady <notifications@github.com> 于2021年1月24日周日 下午5:04写道：

**Comment by AviranAbady** [comment]
@allentown521 Are you sure the stacktrace / crash report comes from a version 1.1.4? 
I can not reproduce the issue, unless you can provide steps to reproduce I'll have to close the issue

**Comment by allentown521** [comment]
Yes, it is.

Aviran Abady <notifications@github.com> 于2021年1月28日周四 上午4:47写道：

**Comment by AviranAbady** [comment]
closed - no steps to reproduce the issue have been provided.
